#!/usr/bin/env bash
##########################################################################
# Copyright 2016 Vuid Pty Ltd 
# https://www.vuid.com
#
# This file is part of tredly-build.
#
# tredly-build is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tredly-build is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tredly-build.  If not, see <http://www.gnu.org/licenses/>.
##########################################################################

# Sanity checks - make sure packages we need are installed
check_for_zfs

show_help "list -- Lists containers.

Examples:

    $(basename "$0") list containers --sort=uuid
    $(basename "$0") list partition
    $(basename "$0") list partition <partitionname>

Options:
    -s <jid|uuid|state|name|ip4|storage|created>  Sorts results by relevant column.
    -h|--help|--usage  Displays this help text"

case "${_SUBCOMMANDS[0]}" in
    containers)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 3 ]]; then
            exit_with_error "Too many arguments received."
        fi

        # list the containers
        list_containers "${_SUBCOMMANDS[1]}" "${_SUBCOMMANDS[2]}"

    ;;
    partitions)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 1 ]]; then
            exit_with_error "Too many arguments received."
        fi
        
        partition_list
    ;;
    *)
        exit_with_error "Unknown list command \"${_SUBCOMMANDS[0]}\""
    ;;
esac

echo "--------------------"