#!/usr/bin/env bash
##########################################################################
# Copyright 2016 Vuid Pty Ltd 
# https://www.vuid.com
#
# This file is part of tredly-build.
#
# tredly-build is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tredly-build is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tredly-build.  If not, see <http://www.gnu.org/licenses/>.
##########################################################################

# commands require running as root
cmn_assert_running_as_root

# Sanity checks - make sure packages we need are installed
check_for_zfs
check_for_ipfw

show_help "Available Commands:
    container
    ---------
    Description:
        Replaces a container with the one specified by Tredlyfile.
        This command attempts to find a container to replace. If no container
        to replace was found, the new container is created anyway.
    
    Options:
        --path=          Provide an alternate path to a Tredlyfile
        --containerName= Override the container name
        --ip4_addr=      Manually specify the networking details for the new 
                         container. Format: <interface>|<ip4 address>/<cidr>
                        
    Examples:
        $(basename "$0") replace container customer1 --path=/path/to/container
"

case "${_SUBCOMMANDS[0]}" in
    container)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 3 ]]; then
            exit_with_error "Too many arguments received."
        fi
        
        # update the container
        container_replace "${_SUBCOMMANDS[1]}" "${_SUBCOMMANDS[2]}"
    ;;
    *)
        exit_with_error "Unknown replace command '${_SUBCOMMANDS[0]}'"
    ;;
esac
